// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2XfhpPnU-Xy6QILoL7hGkGmegFYFNDWg',
    appId: '1:587105097302:web:20298473e4b0a10e840df7',
    messagingSenderId: '587105097302',
    projectId: 'foodislife-a25f6',
    authDomain: 'foodislife-a25f6.firebaseapp.com',
    storageBucket: 'foodislife-a25f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_iErXOw_WR5IYGVfQh148EdNlDSWScQ8',
    appId: '1:587105097302:android:1b8790dd89cf7a3c840df7',
    messagingSenderId: '587105097302',
    projectId: 'foodislife-a25f6',
    storageBucket: 'foodislife-a25f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTDgvXFEQcDqcu-71XEfrUPgZlEBalHvQ',
    appId: '1:587105097302:ios:78b2691d85649a3e840df7',
    messagingSenderId: '587105097302',
    projectId: 'foodislife-a25f6',
    storageBucket: 'foodislife-a25f6.appspot.com',
    iosBundleId: 'com.example.cookin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTDgvXFEQcDqcu-71XEfrUPgZlEBalHvQ',
    appId: '1:587105097302:ios:a3b71b9d97c10b5f840df7',
    messagingSenderId: '587105097302',
    projectId: 'foodislife-a25f6',
    storageBucket: 'foodislife-a25f6.appspot.com',
    iosBundleId: 'com.example.cookin.RunnerTests',
  );
}
